---
- name: Configure Jenkins
  hosts: jenkins

  vars:
    java_packages:
      - java-1.8.0-openjdk-devel

    solita_jenkins_plugins:
      - git
      - copyartifact
      - build-pipeline-plugin
      - delivery-pipeline-plugin
      - build-name-setter
      - cloudbees-folder
      - timestamper
      - ws-cleanup

    solita_ansible_version: 2.1.0.0

  pre_tasks:
    - name: Install initscripts (for Jenkins)
      yum: name=initscripts state=present

    # Work around https://github.com/geerlingguy/ansible-role-jenkins/issues/47
    - name: Fetch Jenkins 1.658
      get_url:
        url: http://pkg.jenkins-ci.org/redhat/jenkins-1.658-1.1.noarch.rpm
        dest: /tmp/jenkins-1.658-1.1.noarch.rpm

    - name: Install Jenkins 1.658
      yum: name=/tmp/jenkins-1.658-1.1.noarch.rpm

  roles:
    - name: solita.jenkins
      tags: jenkins

    - name: solita.ansible
      tags: ansible

  tasks:
    - name: Configure Git for Jenkins
      become: yes
      become_user: jenkins
      command: "git config --global '{{ item.k }}' '{{ item.v }}'"
      with_items:
        - { k: user.name, v: Jenkins }
        - { k: user.email, v: jenkins@example.com }

    - name: Install Maven
      yum: name=maven state=installed

    - name: Generate SSH key for Jenkins
      user: name=jenkins generate_ssh_key=yes

    - name: Fetch Jenkins' public key
      fetch:
        src: /var/lib/jenkins/.ssh/id_rsa.pub
        dest: "{{ inventory_dir }}/jenkins_id_rsa.pub"
        flat: yes

- hosts: jenkins_root_access
  tasks:
    - name: Give Jenkins root access to other hosts
      authorized_key: "user=root key='{{ item }}'"
      with_file:
        - "{{ inventory_dir }}/jenkins_id_rsa.pub"
