#!/bin/bash
set -eu

cd "$(dirname "$BASH_SOURCE")"
cd ..

read -p "Are you sure you want to (re)provision all hosts in the 'reality' inventories? [yN] " -n 1 -r >&2
echo >&2
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  exit 1
fi

for d in reality/*/; do
  ./ansible-playbook -i "${d}inventory" site.yml
done
