#!/bin/bash
set -eu
cd "$(dirname "$BASH_SOURCE")"

source ../.magritte/util/docker.sh

function replace_host {
  sed -e "s/0\\.0\\.0\\.0/$(./host)/g"
}

function container_port {
  local container="$1"
  local port="${2:-}"
  if container_running "$container"; then
    if [[ -n $port ]]; then
      docker port "$container" "$port" | replace_host
    else
      docker port "$container" | while read -sr line; do
      echo "$container:$line" | replace_host
      done
    fi
  fi
}

if [[ $# -eq 0 ]]; then
  for x in *; do
    if [[ -d $x ]]; then
      container_port "$x"
    fi
  done
else
  container_port $@
fi
