---
- name: Configure app servers
  hosts: app

  vars:
    java_packages:
      - openjdk-8-jdk

  pre_tasks:
    - name: Add OpenJDK PPA (for Java 8)
      apt_repository: repo="ppa:openjdk-r/ppa"

  roles:
    - geerlingguy.java

  tasks:
    - include_vars: app_vars.yml

    - name: Create the application user and directory
      user:
        name: "{{ app_user }}"
        home: "{{ app_dir }}"
        system: yes
