---
- name: Configure Jenkins
  hosts: jenkins

  vars:
    java_packages:
      - openjdk-8-jdk

    solita_jenkins_plugins:
      - git
      - copyartifact
      - build-pipeline-plugin
      - delivery-pipeline-plugin
      - build-name-setter
      - cloudbees-folder
      - timestamper
      - ws-cleanup

    solita_ansible_version: 2.1.0.0

  pre_tasks:
    - name: Add OpenJDK PPA (for Java 8)
      apt_repository: repo="ppa:openjdk-r/ppa"

    # Work around https://github.com/geerlingguy/ansible-role-jenkins/issues/47
    - name: Fetch Jenkins 1.658
      get_url:
        url: http://pkg.jenkins-ci.org/debian/binary/jenkins_1.658_all.deb
        dest: /tmp/jenkins_1.658_all.deb

    - name: Install Jenkins 1.658
      apt: deb=/tmp/jenkins_1.658_all.deb

  roles:
    - name: solita.jenkins
      tags: jenkins

    - name: solita.ansible
      tags: ansible

  tasks:
    - name: Configure Git for Jenkins
      become: yes
      become_user: jenkins
      command: "git config --global '{{ item.k }}' '{{ item.v }}'"
      with_items:
        - { k: user.name, v: Jenkins }
        - { k: user.email, v: jenkins@example.com }

    - name: Install Maven
      apt: name=maven state=installed

    - name: Generate SSH key for Jenkins
      user: name=jenkins generate_ssh_key=yes

    - name: Fetch Jenkins' public key
      fetch:
        src: /var/lib/jenkins/.ssh/id_rsa.pub
        dest: "{{ inventory_dir }}/jenkins_id_rsa.pub"
        flat: yes

- hosts: jenkins_root_access
  tasks:
    - name: Give Jenkins root access to other hosts
      authorized_key: "user=root key='{{ item }}'"
      with_file:
        - "{{ inventory_dir }}/jenkins_id_rsa.pub"
