---
- src: https://github.com/solita/ansible-role-solita.jenkins.git
  version: v1.0.2
  name: solita.jenkins

- src: https://github.com/solita/ansible-role-solita.ansible.git
  version: v1.0.0
  name: solita.ansible
